services:
  api:
    build:
      target: api
    ports:
     - '8000:8000'
    volumes:
     - './api:/api'
    extends:
      file: common_services.yaml
      service: common

  socket:
    build:
      target: socket
    ports:
      - '9999:9999'
    volumes:
     - './sockets:/sockets'
    extends:
      file: common_services.yaml
      service: common


  timescaledb:
    image: timescale/timescaledb-ha:pg17
    ports:
      - '5432:5432'
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 2s
      retries: 5
      start_period: 10s
      timeout: 5s
    