services:
  web:
    build: .
    ports:
     - '8000:8000'
    volumes:
     - './app:/app'
    env_file: .env
    depends_on:
      timescaledb:
        condition: service_healthy

  timescaledb:
    image: timescale/timescaledb-ha:pg17
    ports:
      - '5432:5432'
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 2s
      retries: 5
      start_period: 10s
      timeout: 5s
    