"""add items table

Revision ID: 4d80e413138e
Revises: db84b7559936
Create Date: 2025-06-17 18:40:52.728437

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4d80e413138e"
down_revision: Union[str, Sequence[str], None] = "db84b7559936"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

TABLE_NAME = "itemcount"
TIME_COLUMN = "time"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        TABLE_NAME,
        sa.Column("item_name", sa.Text(), nullable=False),
        sa.Column("item_count", sa.Integer(), nullable=False),
        sa.Column(
            "time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("item_name", "item_count", "time"),
    )
    op.execute(f"SELECT create_hypertable('{TABLE_NAME}', by_range('{TIME_COLUMN}'));")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("itemcount")
    # ### end Alembic commands ###
