"""add items table

Revision ID: d8e6715f2475
Revises: db84b7559936
Create Date: 2025-06-25 23:59:20.335884

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d8e6715f2475"
down_revision: Union[str, Sequence[str], None] = "db84b7559936"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

TABLE_NAME = "itemcount"
TIME_COLUMN = "time"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        TABLE_NAME,
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("item_name", sa.Text(), nullable=False),
        sa.Column("item_count", sa.Integer(), nullable=False),
        sa.Column(
            TIME_COLUMN,
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("uuid", TIME_COLUMN),
    )
    op.execute(
        f"SELECT create_hypertable('{TABLE_NAME}', by_range('{TIME_COLUMN}', INTERVAL '1 day'));"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(TABLE_NAME)
    # ### end Alembic commands ###
