"""base

Revision ID: db84b7559936
Revises:
Create Date: 2025-06-17 17:52:26.583034

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "db84b7559936"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
